Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.10.100"

  config.vm.synced_folder "C:/Users/shahi/OneDrive/Desktop/devops_eng99/provisioning/starter-code", "/home/vagrant/app"

  config.vm.provision "shell", path: "environment/provision.sh"
  
end
